/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author juan.ucan
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        menuBarInicio = new javax.swing.JMenuBar();
        menuCaptura = new javax.swing.JMenu();
        menuItemAAguila = new javax.swing.JMenuItem();
        menuItemAConejo = new javax.swing.JMenuItem();
        menuItemASerpiente = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuItemCAguilas = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 51, 153));
        lbTitulo.setText("Estudio del Movimiento de Animales");

        lbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/animales.jpeg"))); // NOI18N

        menuCaptura.setText("Captura");

        menuItemAAguila.setText("Águila");
        menuItemAAguila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAAguilaActionPerformed(evt);
            }
        });
        menuCaptura.add(menuItemAAguila);

        menuItemAConejo.setText("Conejo");
        menuCaptura.add(menuItemAConejo);

        menuItemASerpiente.setText("Serpiente");
        menuItemASerpiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemASerpienteActionPerformed(evt);
            }
        });
        menuCaptura.add(menuItemASerpiente);

        menuBarInicio.add(menuCaptura);

        menuConsultas.setText("Consultas");

        menuItemCAguilas.setText("Águilas");
        menuItemCAguilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCAguilasActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemCAguilas);

        menuBarInicio.add(menuConsultas);

        menuEdicion.setText("Edición");

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuEdicion.add(menuItemSalir);

        menuBarInicio.add(menuEdicion);

        setJMenuBar(menuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(32, 32, 32)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAAguilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAAguilaActionPerformed
        // TODO add your handling code here:
        new FrmCapturaAguila().setVisible(true);
    }//GEN-LAST:event_menuItemAAguilaActionPerformed

    private void menuItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSalirMouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_menuItemSalirMouseClicked

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemASerpienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemASerpienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemASerpienteActionPerformed

    private void menuItemCAguilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCAguilasActionPerformed
        // TODO add your handling code here:
        new FrmConsultaAguila().setVisible(true);
    }//GEN-LAST:event_menuItemCAguilasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuBar menuBarInicio;
    private javax.swing.JMenu menuCaptura;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuItemAAguila;
    private javax.swing.JMenuItem menuItemAConejo;
    private javax.swing.JMenuItem menuItemASerpiente;
    private javax.swing.JMenuItem menuItemCAguilas;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
