
package vista;



public class CalculadoraP extends javax.swing.JFrame {

    private String cadenaNumeros = "";
    private String operacion = "nula";
    private double primerNumero , resultado;
    private boolean activado = true;
    private boolean punto = true;
    
    public CalculadoraP() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Calculadora de gobierno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bnt_CE = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_sqr = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        errores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 580));
        setPreferredSize(new java.awt.Dimension(340, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperacion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(51, 51, 51));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 310, 59));

        txtResultado.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(51, 51, 51));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 310, 63));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, 140));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bnt_CE.setBackground(new java.awt.Color(204, 204, 204));
        bnt_CE.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        bnt_CE.setText("CE");
        bnt_CE.setBorderPainted(false);
        bnt_CE.setFocusPainted(false);
        bnt_CE.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bnt_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_CEActionPerformed(evt);
            }
        });
        jPanel2.add(bnt_CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 20, 80, 60));

        btn_C.setBackground(new java.awt.Color(204, 204, 204));
        btn_C.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_C.setText("C");
        btn_C.setBorderPainted(false);
        btn_C.setFocusPainted(false);
        btn_C.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        jPanel2.add(btn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 60));

        btn_punto.setBackground(new java.awt.Color(204, 204, 204));
        btn_punto.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_punto.setText(".");
        btn_punto.setBorderPainted(false);
        btn_punto.setFocusPainted(false);
        btn_punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 50));

        btn_sqr.setBackground(new java.awt.Color(204, 204, 204));
        btn_sqr.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_sqr.setText("√");
        btn_sqr.setBorderPainted(false);
        btn_sqr.setFocusPainted(false);
        btn_sqr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sqr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        btn_division.setBackground(new java.awt.Color(204, 204, 204));
        btn_division.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_division.setText("/");
        btn_division.setBorderPainted(false);
        btn_division.setFocusPainted(false);
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 50));

        btn_7.setBackground(new java.awt.Color(204, 204, 204));
        btn_7.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_7.setText("7");
        btn_7.setBorderPainted(false);
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 50));

        btn_4.setBackground(new java.awt.Color(204, 204, 204));
        btn_4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_4.setText("4");
        btn_4.setBorderPainted(false);
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, 50));

        btn_1.setBackground(new java.awt.Color(204, 204, 204));
        btn_1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_1.setText("1");
        btn_1.setBorderPainted(false);
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, 50));

        btn_8.setBackground(new java.awt.Color(204, 204, 204));
        btn_8.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_8.setText("8");
        btn_8.setBorderPainted(false);
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 50));

        btn_5.setBackground(new java.awt.Color(204, 204, 204));
        btn_5.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_5.setText("5");
        btn_5.setBorderPainted(false);
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, 50));

        btn_2.setBackground(new java.awt.Color(204, 204, 204));
        btn_2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_2.setText("2");
        btn_2.setBorderPainted(false);
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 50, 50));

        btn_0.setBackground(new java.awt.Color(204, 204, 204));
        btn_0.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_0.setText("0");
        btn_0.setBorderPainted(false);
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 50, 50));

        btn_9.setBackground(new java.awt.Color(204, 204, 204));
        btn_9.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_9.setText("9");
        btn_9.setBorderPainted(false);
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 50));

        btn_6.setBackground(new java.awt.Color(204, 204, 204));
        btn_6.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_6.setText("6");
        btn_6.setBorderPainted(false);
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 50, 50));

        btn_3.setBackground(new java.awt.Color(204, 204, 204));
        btn_3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_3.setText("3");
        btn_3.setBorderPainted(false);
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 50));

        btn_multi.setBackground(new java.awt.Color(204, 204, 204));
        btn_multi.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_multi.setText("*");
        btn_multi.setBorderPainted(false);
        btn_multi.setFocusPainted(false);
        btn_multi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 50, 50));

        btn_resta.setBackground(new java.awt.Color(204, 204, 204));
        btn_resta.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_resta.setText("-");
        btn_resta.setBorderPainted(false);
        btn_resta.setFocusPainted(false);
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 50));

        btn_suma.setBackground(new java.awt.Color(204, 204, 204));
        btn_suma.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_suma.setText("+");
        btn_suma.setBorderPainted(false);
        btn_suma.setFocusPainted(false);
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 50, 50));

        btn_igual.setBackground(new java.awt.Color(204, 204, 204));
        btn_igual.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        btn_igual.setText("=");
        btn_igual.setBorderPainted(false);
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 380));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        errores.setBackground(new java.awt.Color(204, 204, 204));
        errores.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        errores.setText("Errores");
        errores.setBorderPainted(false);
        errores.setFocusPainted(false);
        errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erroresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(errores)
                .addGap(0, 262, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        txtOperacion.setText("");
        txtResultado.setText("");
        cadenaNumeros = "";
        operacion = "nula";
        activado = true;
        punto = true;
        
    }//GEN-LAST:event_btn_CActionPerformed

    private void bnt_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_CEActionPerformed
        int tamaño = cadenaNumeros.length();
        if(tamaño > 0){
           if(tamaño == 1){
             cadenaNumeros = "0";
           }else{
          cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() - 1);
        }
        txtOperacion.setText(cadenaNumeros);
        }
    }//GEN-LAST:event_bnt_CEActionPerformed
 
    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        if (punto == true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
            }else{
               cadenaNumeros += ".";
            }
            txtOperacion.setText(cadenaNumeros);
            punto = false; 
        } 
        
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrActionPerformed
        primerNumero = Double.parseDouble(cadenaNumeros); 
        txtResultado.setText("sqrt("+cadenaNumeros+")");
        resultado = Math.sqrt(primerNumero);
        txtOperacion.setText(String.format("%.2f", resultado));
        cadenaNumeros = String.valueOf(resultado);
        operacion = "raiz";
        punto = true;
        
    }//GEN-LAST:event_btn_sqrActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
      if(activado == true){
          primerNumero = Double.parseDouble(cadenaNumeros);
          txtResultado.setText(cadenaNumeros + " / ");
          cadenaNumeros = "";
          operacion = "dividir";
          
          activado = false;
          punto = true;
        }        
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "7";
        }else{
            cadenaNumeros += "7";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
       
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
      if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "4";
        }else{
            cadenaNumeros += "4";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
               
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
       if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "1";
        }else{
            cadenaNumeros += "1";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso 
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "8";
        }else{
            cadenaNumeros += "8";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
        
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
         if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "5";
        }else{
            cadenaNumeros += "5";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
        
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
       if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "2";
        }else{
            cadenaNumeros += "2";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
       
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "0";
        }else{
            cadenaNumeros += "0";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso 
        
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
       if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "9";
        }else{
            cadenaNumeros += "9";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso
                
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
       if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "6";
        }else{
            cadenaNumeros += "6";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso 
        
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
       if(txtOperacion.getText().equals("0")){
            cadenaNumeros = "3";
        }else{
            cadenaNumeros += "3";
        }
        txtOperacion.setText(cadenaNumeros);
        activado = true;//Booleano indica que la calculadora esta en uso 
        
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        if(activado == true){
          primerNumero = Double.parseDouble(cadenaNumeros);
          txtResultado.setText(cadenaNumeros + " * ");
          cadenaNumeros = "";
          operacion = "multiplicar";
          
          activado = false;
          punto = true;
        }
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
      if(activado == true){
          primerNumero = Double.parseDouble(cadenaNumeros);
          txtResultado.setText(cadenaNumeros + " - ");
          cadenaNumeros = "";
          operacion = "restar";
          
          activado = false;
          punto = true;
          
        }        
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        if(activado == true){
          primerNumero = Double.parseDouble(cadenaNumeros);
          txtResultado.setText(cadenaNumeros + " + ");
          cadenaNumeros = "";
          operacion = "suma";
          
          activado = false;
          punto = true;
          
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        double segundoNumero;
        
        if(operacion.equals("nula")){
            txtOperacion.setText("cadenaNumeros");
        }
        
        else if(operacion.equals("suma")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            
            txtOperacion.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);//valueOf convierte el double a string
            operacion = "nula";
        }
        else if(operacion.equals("restar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            
            txtOperacion.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);//valueOf convierte el double a string
            operacion = "nula";
        }
        else if(operacion.equals("multiplicar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            
            txtOperacion.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);//valueOf convierte el double a string
            operacion = "nula";
        }
        else if(operacion.equals("dividir")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            
            if(segundoNumero == 0){
               txtOperacion.setText("No se divide por 0");
            }else{
                resultado = primerNumero / segundoNumero;
            
            txtOperacion.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);//valueOf convierte el double a string
            operacion = "nula";
            }
            
        }
        
        txtResultado.setText("");
        activado = true;
    }//GEN-LAST:event_btn_igualActionPerformed

    private void erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erroresActionPerformed
        Errores venErrores = new Errores();
        
        venErrores.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_erroresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraP().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_CE;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_sqr;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton errores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
